name: First Workflow
on: workflow_dispatch
jobs: 
  first-job-modified: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye"
